name: Conditional Workflow

on:
  push:
    paths:
      - "backend/**"

jobs:
  conditional-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend Image
        run: echo "Backend Image is building"