name: Cronjob Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cronjob-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cronjob Step
        run: |
          echo  "Hello, cronjob"
          echo  "Again hello"