name: Value Pass Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        default: 'Unnamed'

jobs:
  get-value-pass-workflow-job:
    runs-on: ubuntu-latest
    outputs:
      greetings_message: ${{ steps.generate-message.outputs.message }}

    steps:
      - name: Generate Greetings Message
        id: generate-message
        run: |
          echo "message=Hello, ${{ github.event.inputs.name }}!" >> $GITHUB_OUTPUT

  print-value-pass-workflow-job:
    runs-on: ubuntu-latest
    needs: [get-value-pass-workflow-job]

    steps:
      - name: Print Greetings Message
        run: |
          echo "${{ needs.get-value-pass-workflow-job.outputs.greetings_message }}"